language: ruby

git:
  depth: 10

cache: bundler

rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
    - master

before_install:
  - gem update --system

install:
  - gem install bundler --no-ri --no-rdoc
  - bundle install

script:
  - bundle exec jekyll clean
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external --assume-extension --allow-hash-href --check-html