# Site settings
title: Marthin's Blogs
header-img: img/home-bg.jpg
email: andy@marthin@gmail.com
description: "Andy Marthin Christo Web Developer, Anime Lover, Linux User yang berdomisili di palu. blog ini bertujuan untuk mendokumentasikan kehidupan dan apa yang sedang dipelajari oleh andy marthin christo"
baseurl: ""
url: "http://blog.marthin.web.id"
author: Andy Marthin
twitter_username: AndyMarthin
github_username:  andymarthin
facebook_username:  andy.christo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]