# Site settings
title: Marthin's Blogs
header-img: img/home-bg.jpg
email: andy@marthin.web.id
description: "Andy Marthin Christo Web Developer, Anime Lover, Linux User yang berdomisili di palu. blog ini bertujuan untuk mendokumentasikan kehidupan dan apa yang sedang dipelajari oleh andy marthin christo"
baseurl: ""
url: "https://blog.marthin.web.id"
enforce_ssl: blog.marthin.web.id
author: Andy Marthin
twitter_username: AndyMarthin
github_username:  andymarthin
facebook_username:  andy.christo
email: "andy@marthin.web.id"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5

# Google Analytics
google_analytics_tracking_id: UA-66860547-1
